#!/usr/bin/env bash
#
# Generates frontend runtime config from Terraform outputs, uploads the
# frontend zip to the manual operations bucket, and starts an Amplify deployment.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./deploy-frontend.sh -e <environment>

Generates frontend-website/config.js from terraform output -json, zips
frontend-website/, uploads it to S3, and starts an Amplify deployment.
EOF
}

ENVIRONMENT=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    -env|-e)
      ENVIRONMENT="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown argument '$1'" >&2
      usage
      exit 1
      ;;
  esac
done

if [ -z "$ENVIRONMENT" ]; then
  echo "Error: -e <environment> is required." >&2
  usage
  exit 1
fi

if [ "$ENVIRONMENT" != "dev" ] && [ "$ENVIRONMENT" != "prod" ]; then
  echo "Error: -e <environment> must be one of: dev, prod." >&2
  usage
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "Error: jq is required to read terraform output -json." >&2
  exit 1
fi

if ! command -v aws >/dev/null 2>&1; then
  echo "Error: aws CLI was not found in PATH." >&2
  exit 1
fi

if ! command -v zip >/dev/null 2>&1; then
  echo "Error: zip was not found in PATH." >&2
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  echo "Error: curl was not found in PATH." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TERRAFORM_ROOT="${REPO_ROOT}/infrastructure/terraform/root"
BACKEND_CONFIG="${TERRAFORM_ROOT}/backend.hcl"
FRONTEND_DIR="${REPO_ROOT}/frontend-website"
CONFIG_JS="${FRONTEND_DIR}/config.js"
BUILD_DIR="$(mktemp -d)"
BUILD_ZIP="${BUILD_DIR}/frontend.zip"

cleanup() {
  rm -f "$CONFIG_JS"
  rm -rf "$BUILD_DIR"
}
trap cleanup EXIT

if [ ! -d "$FRONTEND_DIR" ]; then
  echo "Error: frontend directory not found: ${FRONTEND_DIR}" >&2
  exit 1
fi

if [ ! -f "$BACKEND_CONFIG" ]; then
  echo "Error: backend config not found: ${BACKEND_CONFIG}" >&2
  exit 1
fi

BACKEND_REGION="$(sed -nE 's/^[[:space:]]*region[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' "$BACKEND_CONFIG" | tail -n 1)"
if [ -z "$BACKEND_REGION" ]; then
  echo "Error: region not found in backend config: ${BACKEND_CONFIG}" >&2
  exit 1
fi

export AWS_REGION="$BACKEND_REGION"
export AWS_DEFAULT_REGION="$BACKEND_REGION"
export AWS_SDK_LOAD_CONFIG=1

if [ -n "${AWS_PROFILE:-}" ]; then
  if PROFILE_CREDS="$(aws configure export-credentials --profile "${AWS_PROFILE}" --format env 2>/dev/null)"; then
    eval "$PROFILE_CREDS"
    unset AWS_PROFILE
  fi
fi

echo "Resolving Terraform outputs from: ${TERRAFORM_ROOT}"
TF_OUTPUT_JSON="$(terraform -chdir="$TERRAFORM_ROOT" output -json)"

tf_output() {
  local key="$1"
  local value

  value="$(printf '%s' "$TF_OUTPUT_JSON" | jq -r --arg key "$key" '.[$key].value // empty')"
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    echo "Error: missing Terraform output '${key}'." >&2
    exit 1
  fi

  printf '%s' "$value"
}

AWS_REGION="$(tf_output "aws_region")"
COGNITO_CLIENT_ID="$(tf_output "user_pool_client_id")"
COGNITO_AUTH_DOMAIN="$(tf_output "user_pool_auth_domain")"
FRONTEND_CALLBACK_URL="$(tf_output "frontend_callback_url")"
HTTP_API_URL="$(tf_output "http_api_url")"
APP_ID="$(tf_output "amplify_app_id")"
BRANCH_NAME="$(tf_output "amplify_branch_name")"
OPERATIONS_BUCKET="$(tf_output "operations_bucket_name")"
FRONTEND_ARTIFACT_PREFIX="$(tf_output "frontend_artifact_prefix")"

if [ "$BRANCH_NAME" != "$ENVIRONMENT" ]; then
  echo "Error: requested environment '${ENVIRONMENT}' does not match Terraform output amplify_branch_name '${BRANCH_NAME}'." >&2
  exit 1
fi

S3_KEY="${FRONTEND_ARTIFACT_PREFIX%/}/${BRANCH_NAME}/latest.zip"
S3_URI="s3://${OPERATIONS_BUCKET}/${S3_KEY}"

echo "=========================================="
echo " Frontend Deployment"
echo "=========================================="
echo "  Environment : ${ENVIRONMENT}"
echo "  Amplify App : ${APP_ID}"
echo "  Branch      : ${BRANCH_NAME}"
echo "  Artifact    : ${S3_URI}"
echo "  API URL     : ${HTTP_API_URL}"
echo "  Callback    : ${FRONTEND_CALLBACK_URL}"
echo "=========================================="

echo ""
echo "==> Generating frontend runtime config..."
cat > "$CONFIG_JS" <<EOF
// config.js - generated by deploy-frontend.sh at deploy time. Do not commit.
window.__UNI_PORTAL_CONFIG__ = {
  region: "${AWS_REGION}",
  cognitoClientId: "${COGNITO_CLIENT_ID}",
  cognitoAuthDomain: "${COGNITO_AUTH_DOMAIN}",
  callbackUrl: "${FRONTEND_CALLBACK_URL}",
  apiUrl: "${HTTP_API_URL}"
};
EOF

echo "==> Zipping frontend website..."
(
  cd "$FRONTEND_DIR"
  zip -r "$BUILD_ZIP" . \
    --exclude ".DS_Store" \
    --exclude "__MACOSX/*" \
    >/dev/null
)

echo "==> Removing generated config.js from source tree..."
rm -f "$CONFIG_JS"

echo "==> Uploading to ${S3_URI}..."
aws --region "$AWS_REGION" s3 cp "$BUILD_ZIP" "$S3_URI"

echo "==> Creating Amplify deployment job..."
DEPLOYMENT_JSON="$(aws --region "$AWS_REGION" amplify create-deployment \
  --app-id "$APP_ID" \
  --branch-name "$BRANCH_NAME")"

JOB_ID="$(printf '%s' "$DEPLOYMENT_JSON" | jq -r '.jobId // empty')"
UPLOAD_URL="$(printf '%s' "$DEPLOYMENT_JSON" | jq -r '.zipUploadUrl // empty')"

if [ -z "$JOB_ID" ] || [ -z "$UPLOAD_URL" ]; then
  echo "Error: failed to create Amplify deployment job (missing jobId or zipUploadUrl)." >&2
  exit 1
fi

echo "==> Uploading frontend zip to Amplify upload URL..."
curl -sS --fail -X PUT -T "$BUILD_ZIP" "$UPLOAD_URL" >/dev/null

echo "==> Starting Amplify deployment..."
aws --region "$AWS_REGION" amplify start-deployment \
  --app-id "$APP_ID" \
  --branch-name "$BRANCH_NAME" \
  --job-id "$JOB_ID"

echo ""
echo "Frontend deployment started."
echo "Live URL: https://${BRANCH_NAME}.${APP_ID}.amplifyapp.com"
